### ISSUE TITLE
🤦🏼‍♂️ Only single icons used for admonitions. 🖌️

### ISSUE THREAD

**Issue by yokwejuste** [unicef/inventory-hugo-theme#91] opened 2022-04-04 01:22 UTC
# Summary
This issue is derived from #64 and #66. And explained bellow.
Improvement in user experience is the main focus or idea behind this repository. Now visualizing only one icon for different admonitions and alerts can stuck. The only one icon used so far, check it below.
![image](https://user-images.githubusercontent.com/71908316/161458663-40ac019a-2f91-4157-9eea-2382a38fbbd6.png)

# Background
UX is something that constantly needs updates and reviews. Let's improve that content by adding some icons for warnings and others and obviously it should correspond to what we are trying to show up.

**Is the improvement related to a problem? Describe the problem**:
The improvement is not actually related to a problem. The only need here will be to change them in answer to the UX we're trying to improve.
![image](https://user-images.githubusercontent.com/71908316/161458648-90abbdea-e100-401c-ac9e-73b33eb95554.png)

**What does the improvement look like to you?**:
The improvement looks like this.
![image](https://user-images.githubusercontent.com/71908316/161465326-28f69dff-0caf-44f3-952b-324df595eddc.png)

**Describe any alternatives considered**:
The only alternative here will be to leave the admonitions without icons and avoid unwanted complications. I guess this will look prettier at the end in case the icons are not implemented. The image below speaks louder than I do now.
![image](https://user-images.githubusercontent.com/71908316/161458523-bbf3a706-3885-4676-b2f8-a9c1d0b7caa5.png)

# Details
The human eyes fit best with visual content, stuff like videos and cartoons are best digested by the brain, so as the icons and diagrammatic representations. The image is a clear illustration of this.
![image](https://user-images.githubusercontent.com/71908316/161458804-aad7a184-79f3-45be-a5d3-8c8f63cb3776.png)

# Outcome
The only outcome will be a more sweat user interface and an improved user experience in the broad sense.
![image](https://user-images.githubusercontent.com/71908316/161458986-8320b59d-c972-40bb-b5dd-5102ec2b6af7.png)

**Comment by jwflory** [comment] 2022-04-06 03:11
Unique icons for each admonition were added in PR #83 by @BeeBombshell. This issue is complete! 🥳 Closing as a duplicate of #64 and #66.

**Closed** 2022-04-06 03:11 UTC
Labels: X: duplicate, T: improvement
