### ISSUE TITLE
Shift Layouts in Inventory into this Repository

### ISSUE THREAD

**Issue by Neha9849** [unicef/inventory-hugo-theme#107] opened 2022-06-01 15:38 UTC
# Summary

The layouts for team and cohorts are not present in the Inventory theme. Which makes it hard to implement UI/UX fixes.

# How to reproduce?
1.Add the layouts and partials in the repository
2.Remove them from the Inventory Repository

# Outcome
It will be easier to contribute by this change
The teams and cohorts layouts can also be used in other repositories which uses this theme.

**Comment by jwflory** [comment] 2022-06-02 04:29
This is a partial duplicate of #35, although moving the layouts here in the interim makes them easier to maintain in the short term as we get going with the internship.

As a rule of thumb, our sprints will be more intentional with what issues and tasks are planned for each two-week cycle. This first two-week sprint is more spontaneous since we are getting set up with the project management tools and workflows still. But for the next sprint starting on 13 June, we will want to identify the issues we work on ahead of time and put them on the project board for the next sprint.

**Closed** 2022-06-03 04:19 UTC
Labels: T: improvement
